#container scanning task within Azure DevOps
trigger:
- main
- master
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
    
- task: trivy@1
  inputs:
    version: 'latest'
    path: '.'
    severities: 'CRITICAL,HIGH,MEDIUM'
    ignoreUnfixed: true
    exitCode: '0'
    options: '--scanners vuln,misconfig,secret'
